cdn_provider: ''
favicon:
  mimetype: image/svg+xml
  path: themes/custom/appf/favicon.svg
  url: /themes/custom/appf/favicon.svg
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  appf: 8000
langcode: hu
reset_http_request_cache: ''
table: ''
